name: GCS Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: vb-github-actions-gcs

      # Deploy to GCS
      - name: Deploy via GCS
        run: |
          # Use commit SHA as version folder
          VERSION=${GITHUB_SHA}
          echo "Deploying index.html to version folder: $VERSION"
          
          # Copy only index.html
          gsutil cp index.html gs://github-actions-gcs-475209/$VERSION/index.html
          
          # Optional: also update "latest" folder
          gsutil cp index.html gs://github-actions-gcs-475209/latest/index.html
